<?php echo $this->doctype(); ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <?php
        $NAME_APPLICATION = 'ENAPROC';
        echo $this->headTitle($NAME_APPLICATION)->setSeparator(' - ')->setAutoEscape(false)
        ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js')
        ?>
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate($NAME_APPLICATION) ?></a>
                    <div class="nav-collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Início') ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse-->
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row marketing">
                <?php echo $this->content; ?>
            </div>

            <footer>
                <p class="muted credit pull-left">UNIUV © 2014</p>
                <p class="muted credit pull-right">Desenvolvido por Flávia E. Geisler.</p>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
